package com.cloud.study.service;

import com.cloud.study.domain.HrRoleDto;
import com.cloud.study.domain.HrRoleSearch;
import com.cloud.study.entity.HrRole;
import java.util.List;
/**
*  generated by AddClassPlugin plugin
*/

public interface HrRoleService {
        /**
        * 新增
        * @param hrRoleDto
        */
        void addHrRole(HrRoleDto hrRoleDto);
        /**
        * 修改(删除)
        * @param hrRoleDto
        * @param hrRoleSearch
        */
        void updateByHrRoleSearch(HrRoleDto hrRoleDto, HrRoleSearch hrRoleSearch);
        /**
        * 根据id查询
        * @param id
        * @return
        */
        HrRoleDto findById(Integer id);
        /**
        * 分页list
        * @param hrRoleSearch
        * @return
        */
        List<HrRoleDto> searchByHrRoleSearch(HrRoleSearch hrRoleSearch);
        /**
        * 分页条数
        * @param hrRoleSearch
        * @return
        */
        Long count(HrRoleSearch hrRoleSearch);
}