package com.cloud.study.service;

import com.cloud.study.domain.HrDto;
import com.cloud.study.domain.HrSearch;
import com.cloud.study.entity.Hr;
import java.util.List;
/**
*  generated by AddClassPlugin plugin
*/

public interface HrService {
        /**
        * 新增
        * @param hrDto
        */
        void addHr(HrDto hrDto);
        /**
        * 修改(删除)
        * @param hrDto
        * @param hrSearch
        */
        void updateByHrSearch(HrDto hrDto, HrSearch hrSearch);
        /**
        * 根据id查询
        * @param id
        * @return
        */
        HrDto findById(Integer id);
        /**
        * 分页list
        * @param hrSearch
        * @return
        */
        List<HrDto> searchByHrSearch(HrSearch hrSearch);
        /**
        * 分页条数
        * @param hrSearch
        * @return
        */
        Long count(HrSearch hrSearch);
}