package com.cloud.study.service.impl;

import com.cloud.study.domain.HrRoleDto;
import com.cloud.study.domain.HrRoleSearch;
import com.cloud.study.entity.HrRole;
import com.cloud.study.entity.HrRoleExample;
import com.cloud.study.service.HrRoleService;
import com.cloud.study.dao.HrRoleDao;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import java.util.List;
import java.util.ArrayList;
import org.springframework.beans.BeanUtils;
/**
*  generated by AddClassPlugin plugin
*/

@Service
public class HrRoleServiceImpl implements HrRoleService {

    @Resource
    private HrRoleDao hrRoleDao;

    @Override
    public void addHrRole(HrRoleDto hrRoleDto) {
        HrRole hrRole = dtoToEntity(hrRoleDto);
        hrRoleDao.insert(hrRole);
    }

    @Override
    public void updateByHrRoleSearch(HrRoleDto hrRoleDto, HrRoleSearch hrRoleSearch) {

    }

    @Override
    public HrRoleDto findById(Integer id) {
        HrRole hrRole = hrRoleDao.selectByPrimaryKey(id);
        return hrRole == null ? null : entityToDto(hrRole);
    }

    @Override
    public List<HrRoleDto> searchByHrRoleSearch(HrRoleSearch hrRoleSearch) {
        List<HrRoleDto> hrRoleDtos = new ArrayList<>();
        if(hrRoleSearch != null){
            HrRoleExample hrRoleExample = getSearchExample(hrRoleSearch);

            hrRoleExample.setOrderByClause(hrRoleSearch.getOrderByClause());
            List<HrRole> hrRoles = hrRoleDao.selectByExample(hrRoleExample);
            hrRoles.forEach(hrRole -> hrRoleDtos.add(entityToDto(hrRole)));
        }
        return hrRoleDtos;
    }

    @Override
    public Long count(HrRoleSearch hrRoleSearch) {
        HrRoleExample hrRoleExample = getSearchExample(hrRoleSearch);
        return hrRoleDao.countByExample(hrRoleExample);
    }

    /**
    * 查询条件设置
    * @param hrRoleSearch
    * @return
    */
    private HrRoleExample getSearchExample(HrRoleSearch hrRoleSearch){
        HrRoleExample hrRoleExample = new HrRoleExample();
        HrRoleExample.Criteria criteria = hrRoleExample.createCriteria();
        if(hrRoleSearch ==null){
            return hrRoleExample;
        }
        return hrRoleExample;
    }


    /**
    * entity to dto
    * @param hrRole
    * @return
    */
    private HrRoleDto entityToDto(HrRole hrRole){
        HrRoleDto hrRoleDto = new HrRoleDto();
        BeanUtils.copyProperties(hrRole, hrRoleDto);
        return hrRoleDto;
    }

    /**
    * dto to entity
    * @param hrRoleDto
    * @return
    */
    private HrRole dtoToEntity(HrRoleDto hrRoleDto){
        HrRole hrRole = new HrRole();
        BeanUtils.copyProperties(hrRoleDto, hrRole);
        return hrRole;
    }

}