package com.cloud.study.service.impl;

import com.cloud.study.domain.HrDto;
import com.cloud.study.domain.HrSearch;
import com.cloud.study.entity.Hr;
import com.cloud.study.entity.HrExample;
import com.cloud.study.service.HrService;
import com.cloud.study.dao.HrDao;
import org.apache.commons.lang.StringUtils;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import java.util.List;
import java.util.ArrayList;
import org.springframework.beans.BeanUtils;
/**
*  generated by AddClassPlugin plugin
*/

@Service
public class HrServiceImpl implements HrService {

    @Resource
    private HrDao hrDao;

    @Override
    public void addHr(HrDto hrDto) {
        Hr hr = dtoToEntity(hrDto);
        hrDao.insert(hr);
    }

    @Override
    public void updateByHrSearch(HrDto hrDto, HrSearch hrSearch) {

    }

    @Override
    public HrDto findById(Integer id) {
        Hr hr = hrDao.selectByPrimaryKey(id);
        return hr == null ? null : entityToDto(hr);
    }

    @Override
    public List<HrDto> searchByHrSearch(HrSearch hrSearch) {
        List<HrDto> hrDtos = new ArrayList<>();
        if(hrSearch != null){
            HrExample hrExample = getSearchExample(hrSearch);

            hrExample.setOrderByClause(hrSearch.getOrderByClause());
            List<Hr> hrs = hrDao.selectByExample(hrExample);
            hrs.forEach(hr -> hrDtos.add(entityToDto(hr)));
        }
        return hrDtos;
    }

    @Override
    public Long count(HrSearch hrSearch) {
        HrExample hrExample = getSearchExample(hrSearch);
        return hrDao.countByExample(hrExample);
    }

    /**
    * 查询条件设置
    * @param hrSearch
    * @return
    */
    private HrExample getSearchExample(HrSearch hrSearch){
        HrExample hrExample = new HrExample();
        HrExample.Criteria criteria = hrExample.createCriteria();
        if(hrSearch ==null){
            return hrExample;
        }
        if(!StringUtils.isEmpty(hrSearch.getUserName())){
            criteria.andUsernameEqualTo(hrSearch.getUserName());
        }
        return hrExample;
    }


    /**
    * entity to dto
    * @param hr
    * @return
    */
    private HrDto entityToDto(Hr hr){
        HrDto hrDto = new HrDto();
        BeanUtils.copyProperties(hr, hrDto);
        return hrDto;
    }

    /**
    * dto to entity
    * @param hrDto
    * @return
    */
    private Hr dtoToEntity(HrDto hrDto){
        Hr hr = new Hr();
        BeanUtils.copyProperties(hrDto, hr);
        return hr;
    }

}