package com.cloud.study.domain;
import com.cloud.study.entity.Hr;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class HrDto extends Hr {
}